### ISSUE TITLE
Improve F-Droid support

### ISSUE THREAD

**Issue by M2ck** [JBirdVegas/external_jbirdvegas_mGerrit#49]
mGerrit F-Droid version: 2.111.72

mGerrit Google Play version: 2.111.80

**Comment by JBirdVegas** [comment]
Totally cool with `F-Droid` hosting the app but they are removing the the analytics.  We can't make them apply their patches faster.  Maybe we can make a `productFlavor` with the analytics turned off then they should be able to build right from source.  I'll look into this as an approach from our side but unless I'm misunderstanding what F-Droid is doing it's on them to update to the latest correct?

**Comment by p4r4n01d** [comment]
Agreed. I am happy to help any build customization for F-Droid hosting (such as a config which disables analytics) but am going to stop short of actually building and releasing to F-Droid.

**Comment by est31** [comment]
Hi again! I've prepared the 2.111.84 version for the f-droid build and the flavors patch really helped. I now don't have to touch any java code anymore. There still are some changes I did in my patch:

* Enable machines with less RAM (like me or the f-droid buildserver) to build mgerrit
* Enable machines with an older gradle to build mgerrit without the wrapper. The problem here is that f-droid doesn't use the gradle wrapper but the native system provided gradle. Maybe this is not required for the buildserver, but my local setup of f-droid only worked with that change.
* Remove the fabric dependency from the repo list. Unfortunately f-droid is very strict here, even if the repo isn't used by the flavor it detects a non-whitelisted maven repo and protests. I don't know of a way you or f-droid could solve this, but I'll open an issue with the f-droid developers about this.
* Use a jitpack build of the the rest library instead of a provided jar.

I'll provide a PR for the last change for the case you'd like to have it in upstream as well. It makes sense as its very nice towards the repo size.

**Comment by p4r4n01d** [comment]
Glad to hear that @est31! Of the changes you mentioned I am most interested in the first two points as these may be able to fix Travis and/or the release build server (jenkins), which would be great and speed up the release process.

For 'Remove the fabric dependency from the repo list': If you can find a way to have this working for both flavours, submit a PR so it can be merged into master.

I'll have a look at #57, but will need a lot of testing to make sure nothing is broken.

**Comment by est31** [comment]
Hmm, I'll do a PR with the first two points then.

**Comment by nailyk-fr** [comment]
I just ask on f-droid and told me mGerrit can't be build because of proprietary parts. 
Should I open a new issue or is it on the way? 

Thanks
